### PR TITLE
Update typical MB_LEN_MAX value from 6 to 16

### PR DESCRIPTION
**Pull request by pixelb**

### CODE REVIEW

**Comment by mkerrisk** [comment]
Hi Pádraig,

I much prefer patches over Github pull requests...

On 05/12/2015 06:14 PM, Pádraig Brady wrote:

> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/mkerrisk/man-pages/pull/7
> 
> -- Commit Summary --
> - Update typical MB_LEN_MAX value from 6 to 16
> 
> -- File Changes --
> 
> ```
> M man3/MB_LEN_MAX.3 (2)
> ```

A little more detail is needed, I think. I see that your updated
information is correct, but it would also be good to know
when this detail changed. It looks like it was in glibc 2.2,
so I applied the patch below.

Thanks for the report!

Cheers,

Michael

--- a/man3/MB_LEN_MAX.3
+++ b/man3/MB_LEN_MAX.3
@@ -38,7 +38,7 @@ and
 are totally unrelated.
 In glibc,
 .B MB_LEN_MAX
-is typically 6 while
+is typically 16 (6 in glibc versions earlier than 2.2) while
 .I sizeof(wchar_t)
 is 4.
 .SH SEE ALSO

## 

Michael Kerrisk
Linux man-pages maintainer; http://www.kernel.org/doc/man-pages/
Linux/UNIX System Programming Training: http://man7.org/training/

**Comment by pixelb** [comment]
Yes it was changed with https://sourceware.org/git/?p=glibc.git;a=commit;f=include/limits.h;h=d64b6ad075 though unhelpfully not described.

I guess it's because a single wide char can be converted to two (or more?) chars in an encoding, and this constant needs to deal with all encodings.
For example if some encodings didn't have a combined accent representation, the conversion would be char + char for combining accent. Looking at http://www-01.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.cunu100/critbuf.htm we can see iso-2022-kr can have 7 bytes per char, and that encoding is handled in the above commit, so perhaps 16 = (7 + 1) \* 2) with the extra 1 being added for alignment?

**Comment by pixelb** [comment]
I see MB_LEN_MAX = 4 on musl libc (perhaps because it only deals with UTF8?)

**Comment by pixelb** [comment]
MB_LEN_MAX=4 is enough to deal with any stateless encoding, including UTF8 and GB18030. GLIBC's value of 16 was chosen to support legacy stateful encodings, though these were never in fact added to GLIBC. That info was given by Bruno Haible at http://lists.gnu.org/archive/html/bug-gnulib/2015-05/msg00001.html

**Comment by mkerrisk** [comment]
On 05/14/2015 11:13 AM, Pádraig Brady wrote:

> MB_LEN_MAX=4 is enough to deal with any stateless encoding, including
> UTF8 and GB18030. GLIBC's value of 16 was chosen to support legacy
> stateful encodings, though these were never in fact added to GLIBC.
> That info was given by Bruno Haible at
> http://lists.gnu.org/archive/html/bug-gnulib/2015-05/msg00001.html

Thanks, Pádraig. I'll add a po9inter that discussion as a comment
in the page source.

Cheers,

Michael

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mkerrisk/man-pages/pull/7#issuecomment-101979882

## 

Michael Kerrisk
Linux man-pages maintainer; http://www.kernel.org/doc/man-pages/
Linux/UNIX System Programming Training: http://man7.org/training/

**Pull request closed without merging**
